// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg6n9V6H9tACJmdN3d2-9rrmWlr_Q8ma0',
    appId: '1:988462868363:web:e4da082c37fa60b50bf18e',
    messagingSenderId: '988462868363',
    projectId: 'e-library-325cd',
    authDomain: 'e-library-325cd.firebaseapp.com',
    storageBucket: 'e-library-325cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB1EGZNzPnlpQfWBCeEZ5x2DTLWwzO1Hc',
    appId: '1:988462868363:android:ae9a6f43196b06aa0bf18e',
    messagingSenderId: '988462868363',
    projectId: 'e-library-325cd',
    storageBucket: 'e-library-325cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqGDqA4rOFtdwxq-_ZSF0HRXCjuFb6fH0',
    appId: '1:988462868363:ios:b180e517d42bf7a70bf18e',
    messagingSenderId: '988462868363',
    projectId: 'e-library-325cd',
    storageBucket: 'e-library-325cd.appspot.com',
    iosClientId: '988462868363-mikjk2rlmuj6m9q1khrtlurkif3rkprt.apps.googleusercontent.com',
    iosBundleId: 'com.example.electronicLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqGDqA4rOFtdwxq-_ZSF0HRXCjuFb6fH0',
    appId: '1:988462868363:ios:b180e517d42bf7a70bf18e',
    messagingSenderId: '988462868363',
    projectId: 'e-library-325cd',
    storageBucket: 'e-library-325cd.appspot.com',
    iosClientId: '988462868363-mikjk2rlmuj6m9q1khrtlurkif3rkprt.apps.googleusercontent.com',
    iosBundleId: 'com.example.electronicLibrary',
  );
}
